name: ActionsOnPR
on:
  workflow_run:
    workflows: ['Copy']                    
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]
        
    steps:
      - uses: actions/checkout@v2
        with:
          ref: temp
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}  
      - name: Create folder
        run: |
          mkdir myNewFolder 
          
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Create sln 
        run: dotnet new sln --name t
          
      - name: Add csproj
        run: |
          dotnet sln t.sln add TestConsoleApp.csproj
          dotnet add XUnitTestProject1.csproj reference TestConsoleApp.csproj
          dotnet sln t.sln add XUnitTestProject1.csproj
          dotnet restore t.sln
                  
      - name: Build and test
        run: |
          dotnet build t.sln
          dotnet test XUnitTestProject1.csproj --logger "trx;LogFileName=test-results.trx"   
          
      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results  
          path: ./**/TestResults/*.trx
      
      
 
