name: Copy folder to other branch

on:
  workflow_run:
    workflows: ['mergeAction']                    
    types:
      - completed
  workflow_dispatch:    

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FOLDER_PATH: 'empty'
          TARGET_BRANCH: 'temp'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                        
          git checkout $TARGET_BRANCH       
          git checkout ${GITHUB_REF##*/} -- $files 
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"
          git push origin $TARGET_BRANCH
