name: 'Test Report'
on:
  pull_request
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1.5.0
      with:
        artifact: test-results            
        name: dotnet-trx                  
        path: ./**/TestResults/*.trx                   
        reporter: dotnet-trx   
